Mega

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,15 +1,24 @@
 #!/usr/bin/env bash
-# Made by MEGATHRON
-# transfer the file from our client to the server
-if [ $# -lt 3 ];
-then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
-    exit;
-fi;
+# Made by MEGA
+# Script transfers files from client to server
+# disp Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
+# If less than 3 params transfer to ~/
 
-if [ $# -ge 4 ];
-then
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
-else
-    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
-fi;
+PATH_TO_FILE="$1";
+IP="$2";
+USERNAME="$3";
+PATH_TO_SSH_KEY="$4";
+ERROR="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
+HOST_KEY_RULE="StrictHostKeyChecking=no"
+
+if [ "$#" -lt 3 ]; then
+	echo -e "$ERROR";
+	exit 1;
+fi
+
+if [ "$#" -eq 3 ]; then
+	scp -o "$HOST_KEY_RULE" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
+	exit 0;
+fi
+
+scp -o "$HOST_KEY_RULE" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/";
